/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ObjectApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ObjectApiTests : IDisposable
    {
        private ObjectApi instance;

        public ObjectApiTests()
        {
            instance = new ObjectApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ObjectApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ObjectApi
            //Assert.IsType(typeof(ObjectApi), instance, "instance is a ObjectApi");
        }

        
        /// <summary>
        /// Test AddObject
        /// </summary>
        [Fact]
        public void AddObjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accept = null;
            //System.IO.Stream image = null;
            //ObjectDescription description = null;
            //var response = instance.AddObject(accept, image, description);
            //Assert.IsType<Object> (response, "response is Object");
        }
        
    }

}
