/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing LocalizerLocalizeDescriptionGps
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocalizerLocalizeDescriptionGpsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LocalizerLocalizeDescriptionGps
        //private LocalizerLocalizeDescriptionGps instance;

        public LocalizerLocalizeDescriptionGpsTests()
        {
            // TODO uncomment below to create an instance of LocalizerLocalizeDescriptionGps
            //instance = new LocalizerLocalizeDescriptionGps();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LocalizerLocalizeDescriptionGps
        /// </summary>
        [Fact]
        public void LocalizerLocalizeDescriptionGpsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LocalizerLocalizeDescriptionGps
            //Assert.IsInstanceOfType<LocalizerLocalizeDescriptionGps> (instance, "variable 'instance' is a LocalizerLocalizeDescriptionGps");
        }


        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }
        /// <summary>
        /// Test the property 'Altitude'
        /// </summary>
        [Fact]
        public void AltitudeTest()
        {
            // TODO unit test for the property 'Altitude'
        }
        /// <summary>
        /// Test the property 'Hdop'
        /// </summary>
        [Fact]
        public void HdopTest()
        {
            // TODO unit test for the property 'Hdop'
        }

    }

}
