/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing LocalizationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocalizationResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LocalizationResult
        //private LocalizationResult instance;

        public LocalizationResultTests()
        {
            // TODO uncomment below to create an instance of LocalizationResult
            //instance = new LocalizationResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LocalizationResult
        /// </summary>
        [Fact]
        public void LocalizationResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LocalizationResult
            //Assert.IsInstanceOfType<LocalizationResult> (instance, "variable 'instance' is a LocalizationResult");
        }


        /// <summary>
        /// Test the property 'Camera'
        /// </summary>
        [Fact]
        public void CameraTest()
        {
            // TODO unit test for the property 'Camera'
        }
        /// <summary>
        /// Test the property 'ObjectsInfo'
        /// </summary>
        [Fact]
        public void ObjectsInfoTest()
        {
            // TODO unit test for the property 'ObjectsInfo'
        }
        /// <summary>
        /// Test the property 'SceneId'
        /// </summary>
        [Fact]
        public void SceneIdTest()
        {
            // TODO unit test for the property 'SceneId'
        }
        /// <summary>
        /// Test the property 'Scene'
        /// </summary>
        [Fact]
        public void SceneTest()
        {
            // TODO unit test for the property 'Scene'
        }
        /// <summary>
        /// Test the property 'Surfaces'
        /// </summary>
        [Fact]
        public void SurfacesTest()
        {
            // TODO unit test for the property 'Surfaces'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
