/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing LocalizationResultAllOfSurfaces
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocalizationResultAllOfSurfacesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LocalizationResultAllOfSurfaces
        //private LocalizationResultAllOfSurfaces instance;

        public LocalizationResultAllOfSurfacesTests()
        {
            // TODO uncomment below to create an instance of LocalizationResultAllOfSurfaces
            //instance = new LocalizationResultAllOfSurfaces();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LocalizationResultAllOfSurfaces
        /// </summary>
        [Fact]
        public void LocalizationResultAllOfSurfacesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LocalizationResultAllOfSurfaces
            //Assert.IsInstanceOfType<LocalizationResultAllOfSurfaces> (instance, "variable 'instance' is a LocalizationResultAllOfSurfaces");
        }


        /// <summary>
        /// Test the property 'Frame'
        /// </summary>
        [Fact]
        public void FrameTest()
        {
            // TODO unit test for the property 'Frame'
        }
        /// <summary>
        /// Test the property 'Pose'
        /// </summary>
        [Fact]
        public void PoseTest()
        {
            // TODO unit test for the property 'Pose'
        }

    }

}
