/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing LocalizationResultAllOfScene
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocalizationResultAllOfSceneTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LocalizationResultAllOfScene
        //private LocalizationResultAllOfScene instance;

        public LocalizationResultAllOfSceneTests()
        {
            // TODO uncomment below to create an instance of LocalizationResultAllOfScene
            //instance = new LocalizationResultAllOfScene();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LocalizationResultAllOfScene
        /// </summary>
        [Fact]
        public void LocalizationResultAllOfSceneInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LocalizationResultAllOfScene
            //Assert.IsInstanceOfType<LocalizationResultAllOfScene> (instance, "variable 'instance' is a LocalizationResultAllOfScene");
        }


        /// <summary>
        /// Test the property 'Node'
        /// </summary>
        [Fact]
        public void NodeTest()
        {
            // TODO unit test for the property 'Node'
        }

    }

}
