/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Model3DSceneNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Model3DSceneNodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Model3DSceneNode
        //private Model3DSceneNode instance;

        public Model3DSceneNodeTests()
        {
            // TODO uncomment below to create an instance of Model3DSceneNode
            //instance = new Model3DSceneNode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Model3DSceneNode
        /// </summary>
        [Fact]
        public void Model3DSceneNodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Model3DSceneNode
            //Assert.IsInstanceOfType<Model3DSceneNode> (instance, "variable 'instance' is a Model3DSceneNode");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Fact]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }

    }

}
