/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Model3DPose
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Model3DPoseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Model3DPose
        //private Model3DPose instance;

        public Model3DPoseTests()
        {
            // TODO uncomment below to create an instance of Model3DPose
            //instance = new Model3DPose();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Model3DPose
        /// </summary>
        [Fact]
        public void Model3DPoseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Model3DPose
            //Assert.IsInstanceOfType<Model3DPose> (instance, "variable 'instance' is a Model3DPose");
        }


        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Orientation'
        /// </summary>
        [Fact]
        public void OrientationTest()
        {
            // TODO unit test for the property 'Orientation'
        }

    }

}
