/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StickerDescriptionSticker
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StickerDescriptionStickerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StickerDescriptionSticker
        //private StickerDescriptionSticker instance;

        public StickerDescriptionStickerTests()
        {
            // TODO uncomment below to create an instance of StickerDescriptionSticker
            //instance = new StickerDescriptionSticker();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StickerDescriptionSticker
        /// </summary>
        [Fact]
        public void StickerDescriptionStickerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StickerDescriptionSticker
            //Assert.IsInstanceOfType<StickerDescriptionSticker> (instance, "variable 'instance' is a StickerDescriptionSticker");
        }


        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'StickerText'
        /// </summary>
        [Fact]
        public void StickerTextTest()
        {
            // TODO unit test for the property 'StickerText'
        }

    }

}
