/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StickerDescription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StickerDescriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StickerDescription
        //private StickerDescription instance;

        public StickerDescriptionTests()
        {
            // TODO uncomment below to create an instance of StickerDescription
            //instance = new StickerDescription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StickerDescription
        /// </summary>
        [Fact]
        public void StickerDescriptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StickerDescription
            //Assert.IsInstanceOfType<StickerDescription> (instance, "variable 'instance' is a StickerDescription");
        }


        /// <summary>
        /// Test the property 'Sticker'
        /// </summary>
        [Fact]
        public void StickerTest()
        {
            // TODO unit test for the property 'Sticker'
        }
        /// <summary>
        /// Test the property 'Placeholder'
        /// </summary>
        [Fact]
        public void PlaceholderTest()
        {
            // TODO unit test for the property 'Placeholder'
        }

    }

}
