/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StickerDescriptionPlaceholderProjections
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StickerDescriptionPlaceholderProjectionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StickerDescriptionPlaceholderProjections
        //private StickerDescriptionPlaceholderProjections instance;

        public StickerDescriptionPlaceholderProjectionsTests()
        {
            // TODO uncomment below to create an instance of StickerDescriptionPlaceholderProjections
            //instance = new StickerDescriptionPlaceholderProjections();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StickerDescriptionPlaceholderProjections
        /// </summary>
        [Fact]
        public void StickerDescriptionPlaceholderProjectionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StickerDescriptionPlaceholderProjections
            //Assert.IsInstanceOfType<StickerDescriptionPlaceholderProjections> (instance, "variable 'instance' is a StickerDescriptionPlaceholderProjections");
        }


        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Fact]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

    }

}
