/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ObjectDescription
    /// </summary>
    [DataContract]
    public partial class ObjectDescription :  IEquatable<ObjectDescription>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectDescription" /> class.
        /// </summary>
        /// <param name="sticker">sticker.</param>
        /// <param name="placeholder">placeholder.</param>
        public ObjectDescription(ObjectDescriptionSticker sticker = default(ObjectDescriptionSticker), ObjectDescriptionPlaceholder placeholder = default(ObjectDescriptionPlaceholder))
        {
            this.Sticker = sticker;
            this.Placeholder = placeholder;
        }
        
        /// <summary>
        /// Gets or Sets Sticker
        /// </summary>
        [DataMember(Name="sticker", EmitDefaultValue=false)]
        public ObjectDescriptionSticker Sticker { get; set; }

        /// <summary>
        /// Gets or Sets Placeholder
        /// </summary>
        [DataMember(Name="placeholder", EmitDefaultValue=false)]
        public ObjectDescriptionPlaceholder Placeholder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ObjectDescription {\n");
            sb.Append("  Sticker: ").Append(Sticker).Append("\n");
            sb.Append("  Placeholder: ").Append(Placeholder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ObjectDescription);
        }

        /// <summary>
        /// Returns true if ObjectDescription instances are equal
        /// </summary>
        /// <param name="input">Instance of ObjectDescription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ObjectDescription input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Sticker == input.Sticker ||
                    (this.Sticker != null &&
                    this.Sticker.Equals(input.Sticker))
                ) && 
                (
                    this.Placeholder == input.Placeholder ||
                    (this.Placeholder != null &&
                    this.Placeholder.Equals(input.Placeholder))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Sticker != null)
                    hashCode = hashCode * 59 + this.Sticker.GetHashCode();
                if (this.Placeholder != null)
                    hashCode = hashCode * 59 + this.Placeholder.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
