/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ObjectDescriptionSticker
    /// </summary>
    [DataContract]
    public partial class ObjectDescriptionSticker :  IEquatable<ObjectDescriptionSticker>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectDescriptionSticker" /> class.
        /// </summary>
        /// <param name="path">path.</param>
        /// <param name="stickerText">stickerText.</param>
        public ObjectDescriptionSticker(string path = default(string), string stickerText = default(string))
        {
            this.Path = path;
            this.StickerText = stickerText;
        }
        
        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name="path", EmitDefaultValue=false)]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets StickerText
        /// </summary>
        [DataMember(Name="sticker_text", EmitDefaultValue=false)]
        public string StickerText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ObjectDescriptionSticker {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  StickerText: ").Append(StickerText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ObjectDescriptionSticker);
        }

        /// <summary>
        /// Returns true if ObjectDescriptionSticker instances are equal
        /// </summary>
        /// <param name="input">Instance of ObjectDescriptionSticker to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ObjectDescriptionSticker input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Path == input.Path ||
                    (this.Path != null &&
                    this.Path.Equals(input.Path))
                ) && 
                (
                    this.StickerText == input.StickerText ||
                    (this.StickerText != null &&
                    this.StickerText.Equals(input.StickerText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Path != null)
                    hashCode = hashCode * 59 + this.Path.GetHashCode();
                if (this.StickerText != null)
                    hashCode = hashCode * 59 + this.StickerText.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
