/**
* Augmented City API
* ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
*
* The version of the OpenAPI document: 1.0.0
* Contact: support@vergendo.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param code | State   | Code   |  Description  |   | -- | -- | -- |   | Success | 0 | Operation completed successfully |   | Fail | 1 | Operation failed, message field contains a description |   |  Server error | 2 | Some internal server error occurred  |  
 * @param message 
 */

data class InlineResponse2001Status (
    /* | State   | Code   |  Description  |   | -- | -- | -- |   | Success | 0 | Operation completed successfully |   | Fail | 1 | Operation failed, message field contains a description |   |  Server error | 2 | Some internal server error occurred  |   */
    @Json(name = "code")
    val code: InlineResponse2001Status.Code,
    @Json(name = "message")
    val message: kotlin.String? = null
) {

    /**
    * | State   | Code   |  Description  |   | -- | -- | -- |   | Success | 0 | Operation completed successfully |   | Fail | 1 | Operation failed, message field contains a description |   |  Server error | 2 | Some internal server error occurred  |  
    * Values: _0,_1,_2
    */
    
    enum class Code(val value: kotlin.Int){
        @Json(name = "0") _0(0),
        @Json(name = "1") _1(1),
        @Json(name = "2") _2(2);
    }
}

