/**
* Augmented City API
* ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
*
* The version of the OpenAPI document: 1.0.0
* Contact: support@vergendo.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param user 
 * @param device 
 * @param client 
 * @param name 
 * @param daytime 
 * @param passagesCount 
 */

data class InlineObject3 (
    @Json(name = "user")
    val user: kotlin.String,
    @Json(name = "device")
    val device: kotlin.String,
    @Json(name = "client")
    val client: kotlin.String,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "daytime")
    val daytime: kotlin.String,
    @Json(name = "passages_count")
    val passagesCount: kotlin.Int
)

