/**
* Augmented City API
* ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
*
* The version of the OpenAPI document: 1.0.0
* Contact: support@vergendo.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param points 
 * @param filename 
 */

data class ObjectDescriptionPlaceholderProjections (
    @Json(name = "points")
    val points: kotlin.Array<kotlin.Array<kotlin.Int>>? = null,
    @Json(name = "filename")
    val filename: kotlin.String? = null
)

