/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing LocalizationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LocalizationApiTests : IDisposable
    {
        private LocalizationApi instance;

        public LocalizationApiTests()
        {
            instance = new LocalizationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LocalizationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LocalizationApi
            //Assert.IsType(typeof(LocalizationApi), instance, "instance is a LocalizationApi");
        }

        
        /// <summary>
        /// Test GetObjects
        /// </summary>
        [Fact]
        public void GetObjectsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accept = null;
            //string type = null;
            //string sceneFormat = null;
            //System.IO.Stream file = null;
            //var response = instance.GetObjects(accept, type, sceneFormat, file);
            //Assert.IsType<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test Localize
        /// </summary>
        [Fact]
        public void LocalizeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accept = null;
            //LocalizerLocalizeDescription description = null;
            //System.IO.Stream image = null;
            //var response = instance.Localize(accept, description, image);
            //Assert.IsType<LocalizationResult> (response, "response is LocalizationResult");
        }
        
        /// <summary>
        /// Test Prepare
        /// </summary>
        [Fact]
        public void PrepareTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accept = null;
            //double lat = null;
            //double lon = null;
            //double? alt = null;
            //double? dop = null;
            //var response = instance.Prepare(accept, lat, lon, alt, dop);
            //Assert.IsType<Status> (response, "response is Status");
        }
        
    }

}
