/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing VersionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class VersionApiTests : IDisposable
    {
        private VersionApi instance;

        public VersionApiTests()
        {
            instance = new VersionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VersionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' VersionApi
            //Assert.IsType(typeof(VersionApi), instance, "instance is a VersionApi");
        }

        
        /// <summary>
        /// Test ServerVersionGet
        /// </summary>
        [Fact]
        public void ServerVersionGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            string body = null;
            var response = instance.ServerVersionGet(body);
            //Assert.IsType<string> (response, "response is string");
        }
        
    }

}
