@startuml
== Localize ==
activate Unity
Unity -> Unity : startLocalization
Unity -> Unity : firstLocalization
Unity -> Unity : UploadJPGwithGPS
deactivate Unity

Unity -> UnitySDK : Enqueue Localize Task
activate UnitySDK

note right : Show StickerInfo details
UnitySDK -> UnitySDK : Keep Session if any
note right : Generate proxy class using openapi
UnitySDK -> AugmentedCityAPI : api/localizer/localize 
UnitySDK -> UnitySDK : Update Session params

UnitySDK -> Unity : Localize Resp
deactivate UnitySDK
@enduml

