/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject3
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject3Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject3
        //private InlineObject3 instance;

        public InlineObject3Tests()
        {
            // TODO uncomment below to create an instance of InlineObject3
            //instance = new InlineObject3();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject3
        /// </summary>
        [Fact]
        public void InlineObject3InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject3
            //Assert.IsInstanceOfType<InlineObject3> (instance, "variable 'instance' is a InlineObject3");
        }


        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }
        /// <summary>
        /// Test the property '_Client'
        /// </summary>
        [Fact]
        public void _ClientTest()
        {
            // TODO unit test for the property '_Client'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Daytime'
        /// </summary>
        [Fact]
        public void DaytimeTest()
        {
            // TODO unit test for the property 'Daytime'
        }
        /// <summary>
        /// Test the property 'PassagesCount'
        /// </summary>
        [Fact]
        public void PassagesCountTest()
        {
            // TODO unit test for the property 'PassagesCount'
        }

    }

}
