/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject2
        //private InlineObject2 instance;

        public InlineObject2Tests()
        {
            // TODO uncomment below to create an instance of InlineObject2
            //instance = new InlineObject2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject2
        /// </summary>
        [Fact]
        public void InlineObject2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject2
            //Assert.IsInstanceOfType<InlineObject2> (instance, "variable 'instance' is a InlineObject2");
        }


        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Fact]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }

    }

}
