/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2001Status
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2001StatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2001Status
        //private InlineResponse2001Status instance;

        public InlineResponse2001StatusTests()
        {
            // TODO uncomment below to create an instance of InlineResponse2001Status
            //instance = new InlineResponse2001Status();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2001Status
        /// </summary>
        [Fact]
        public void InlineResponse2001StatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2001Status
            //Assert.IsInstanceOfType<InlineResponse2001Status> (instance, "variable 'instance' is a InlineResponse2001Status");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
