/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing LocalizerLocalizeDescription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocalizerLocalizeDescriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LocalizerLocalizeDescription
        //private LocalizerLocalizeDescription instance;

        public LocalizerLocalizeDescriptionTests()
        {
            // TODO uncomment below to create an instance of LocalizerLocalizeDescription
            //instance = new LocalizerLocalizeDescription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LocalizerLocalizeDescription
        /// </summary>
        [Fact]
        public void LocalizerLocalizeDescriptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LocalizerLocalizeDescription
            //Assert.IsInstanceOfType<LocalizerLocalizeDescription> (instance, "variable 'instance' is a LocalizerLocalizeDescription");
        }


        /// <summary>
        /// Test the property 'Gps'
        /// </summary>
        [Fact]
        public void GpsTest()
        {
            // TODO unit test for the property 'Gps'
        }
        /// <summary>
        /// Test the property 'FocalLengthIn35mmFilm'
        /// </summary>
        [Fact]
        public void FocalLengthIn35mmFilmTest()
        {
            // TODO unit test for the property 'FocalLengthIn35mmFilm'
        }
        /// <summary>
        /// Test the property 'Mirrored'
        /// </summary>
        [Fact]
        public void MirroredTest()
        {
            // TODO unit test for the property 'Mirrored'
        }
        /// <summary>
        /// Test the property 'Rotation'
        /// </summary>
        [Fact]
        public void RotationTest()
        {
            // TODO unit test for the property 'Rotation'
        }

    }

}
