/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ObjectDescriptionPlaceholder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObjectDescriptionPlaceholderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ObjectDescriptionPlaceholder
        //private ObjectDescriptionPlaceholder instance;

        public ObjectDescriptionPlaceholderTests()
        {
            // TODO uncomment below to create an instance of ObjectDescriptionPlaceholder
            //instance = new ObjectDescriptionPlaceholder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ObjectDescriptionPlaceholder
        /// </summary>
        [Fact]
        public void ObjectDescriptionPlaceholderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ObjectDescriptionPlaceholder
            //Assert.IsInstanceOfType<ObjectDescriptionPlaceholder> (instance, "variable 'instance' is a ObjectDescriptionPlaceholder");
        }


        /// <summary>
        /// Test the property 'Projections'
        /// </summary>
        [Fact]
        public void ProjectionsTest()
        {
            // TODO unit test for the property 'Projections'
        }

    }

}
