/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILocalizationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Return objects
        /// </summary>
        /// <remarks>
        /// Localize uploaded image and return objects info and scene
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="type">If not specified type is sticker (optional, default to sticker)</param>
        /// <param name="sceneFormat">If not specified scene_format is none (optional, default to none)</param>
        /// <param name="file">An image to make a query by (optional)</param>
        /// <returns>Object</returns>
        Object GetObjects (string accept, string type = default(string), string sceneFormat = default(string), System.IO.Stream file = default(System.IO.Stream));

        /// <summary>
        /// Return objects
        /// </summary>
        /// <remarks>
        /// Localize uploaded image and return objects info and scene
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="type">If not specified type is sticker (optional, default to sticker)</param>
        /// <param name="sceneFormat">If not specified scene_format is none (optional, default to none)</param>
        /// <param name="file">An image to make a query by (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> GetObjectsWithHttpInfo (string accept, string type = default(string), string sceneFormat = default(string), System.IO.Stream file = default(System.IO.Stream));
        /// <summary>
        /// Localize camera
        /// </summary>
        /// <remarks>
        /// Localize uploaded image. Return camera pose and optional objects info and scene. Objects info and scene are sent on coordinate system change.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="description"></param>
        /// <param name="image">A JPEG-encoded query image</param>
        /// <returns>LocalizationResult</returns>
        LocalizationResult Localize (string accept, LocalizerLocalizeDescription description, System.IO.Stream image);

        /// <summary>
        /// Localize camera
        /// </summary>
        /// <remarks>
        /// Localize uploaded image. Return camera pose and optional objects info and scene. Objects info and scene are sent on coordinate system change.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="description"></param>
        /// <param name="image">A JPEG-encoded query image</param>
        /// <returns>ApiResponse of LocalizationResult</returns>
        ApiResponse<LocalizationResult> LocalizeWithHttpInfo (string accept, LocalizerLocalizeDescription description, System.IO.Stream image);
        /// <summary>
        /// Prepare localization session
        /// </summary>
        /// <remarks>
        /// Prepare for localization for given geolocation. Causes server to load nearby reconstructions for localization. Returns an error when localization in this location is not possible.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="lat">GPS latitude</param>
        /// <param name="lon">GPS longitude</param>
        /// <param name="alt">GPS altitude (optional) (optional)</param>
        /// <param name="dop">GPS HDOP (optional) (optional)</param>
        /// <returns>Status</returns>
        Status Prepare (string accept, double lat, double lon, double? alt = default(double?), double? dop = default(double?));

        /// <summary>
        /// Prepare localization session
        /// </summary>
        /// <remarks>
        /// Prepare for localization for given geolocation. Causes server to load nearby reconstructions for localization. Returns an error when localization in this location is not possible.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="lat">GPS latitude</param>
        /// <param name="lon">GPS longitude</param>
        /// <param name="alt">GPS altitude (optional) (optional)</param>
        /// <param name="dop">GPS HDOP (optional) (optional)</param>
        /// <returns>ApiResponse of Status</returns>
        ApiResponse<Status> PrepareWithHttpInfo (string accept, double lat, double lon, double? alt = default(double?), double? dop = default(double?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILocalizationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Return objects
        /// </summary>
        /// <remarks>
        /// Localize uploaded image and return objects info and scene
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="type">If not specified type is sticker (optional, default to sticker)</param>
        /// <param name="sceneFormat">If not specified scene_format is none (optional, default to none)</param>
        /// <param name="file">An image to make a query by (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> GetObjectsAsync (string accept, string type = default(string), string sceneFormat = default(string), System.IO.Stream file = default(System.IO.Stream));

        /// <summary>
        /// Return objects
        /// </summary>
        /// <remarks>
        /// Localize uploaded image and return objects info and scene
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="type">If not specified type is sticker (optional, default to sticker)</param>
        /// <param name="sceneFormat">If not specified scene_format is none (optional, default to none)</param>
        /// <param name="file">An image to make a query by (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetObjectsAsyncWithHttpInfo (string accept, string type = default(string), string sceneFormat = default(string), System.IO.Stream file = default(System.IO.Stream));
        /// <summary>
        /// Localize camera
        /// </summary>
        /// <remarks>
        /// Localize uploaded image. Return camera pose and optional objects info and scene. Objects info and scene are sent on coordinate system change.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="description"></param>
        /// <param name="image">A JPEG-encoded query image</param>
        /// <returns>Task of LocalizationResult</returns>
        System.Threading.Tasks.Task<LocalizationResult> LocalizeAsync (string accept, LocalizerLocalizeDescription description, System.IO.Stream image);

        /// <summary>
        /// Localize camera
        /// </summary>
        /// <remarks>
        /// Localize uploaded image. Return camera pose and optional objects info and scene. Objects info and scene are sent on coordinate system change.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="description"></param>
        /// <param name="image">A JPEG-encoded query image</param>
        /// <returns>Task of ApiResponse (LocalizationResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<LocalizationResult>> LocalizeAsyncWithHttpInfo (string accept, LocalizerLocalizeDescription description, System.IO.Stream image);
        /// <summary>
        /// Prepare localization session
        /// </summary>
        /// <remarks>
        /// Prepare for localization for given geolocation. Causes server to load nearby reconstructions for localization. Returns an error when localization in this location is not possible.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="lat">GPS latitude</param>
        /// <param name="lon">GPS longitude</param>
        /// <param name="alt">GPS altitude (optional) (optional)</param>
        /// <param name="dop">GPS HDOP (optional) (optional)</param>
        /// <returns>Task of Status</returns>
        System.Threading.Tasks.Task<Status> PrepareAsync (string accept, double lat, double lon, double? alt = default(double?), double? dop = default(double?));

        /// <summary>
        /// Prepare localization session
        /// </summary>
        /// <remarks>
        /// Prepare for localization for given geolocation. Causes server to load nearby reconstructions for localization. Returns an error when localization in this location is not possible.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="lat">GPS latitude</param>
        /// <param name="lon">GPS longitude</param>
        /// <param name="alt">GPS altitude (optional) (optional)</param>
        /// <param name="dop">GPS HDOP (optional) (optional)</param>
        /// <returns>Task of ApiResponse (Status)</returns>
        System.Threading.Tasks.Task<ApiResponse<Status>> PrepareAsyncWithHttpInfo (string accept, double lat, double lon, double? alt = default(double?), double? dop = default(double?));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILocalizationApi : ILocalizationApiSync, ILocalizationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LocalizationApi : ILocalizationApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LocalizationApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LocalizationApi(String basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LocalizationApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public LocalizationApi(Org.OpenAPITools.Client.ISynchronousClient client,Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Return objects Localize uploaded image and return objects info and scene
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="type">If not specified type is sticker (optional, default to sticker)</param>
        /// <param name="sceneFormat">If not specified scene_format is none (optional, default to none)</param>
        /// <param name="file">An image to make a query by (optional)</param>
        /// <returns>Object</returns>
        public Object GetObjects (string accept, string type = default(string), string sceneFormat = default(string), System.IO.Stream file = default(System.IO.Stream))
        {
             Org.OpenAPITools.Client.ApiResponse<Object> localVarResponse = GetObjectsWithHttpInfo(accept, type, sceneFormat, file);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Return objects Localize uploaded image and return objects info and scene
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="type">If not specified type is sticker (optional, default to sticker)</param>
        /// <param name="sceneFormat">If not specified scene_format is none (optional, default to none)</param>
        /// <param name="file">An image to make a query by (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public Org.OpenAPITools.Client.ApiResponse< Object > GetObjectsWithHttpInfo (string accept, string type = default(string), string sceneFormat = default(string), System.IO.Stream file = default(System.IO.Stream))
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'accept' when calling LocalizationApi->GetObjects");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/plain"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }
            if (sceneFormat != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "scene_format", sceneFormat));
            }
            localVarRequestOptions.HeaderParameters.Add("Accept", Org.OpenAPITools.Client.ClientUtils.ParameterToString(accept)); // header parameter
            if (file != null)
            {
                localVarRequestOptions.FileParameters.Add("file", file);
            }


            // make the HTTP request
            var localVarResponse = this.Client.Post< Object >("/get_objects", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetObjects", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Return objects Localize uploaded image and return objects info and scene
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="type">If not specified type is sticker (optional, default to sticker)</param>
        /// <param name="sceneFormat">If not specified scene_format is none (optional, default to none)</param>
        /// <param name="file">An image to make a query by (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> GetObjectsAsync (string accept, string type = default(string), string sceneFormat = default(string), System.IO.Stream file = default(System.IO.Stream))
        {
             Org.OpenAPITools.Client.ApiResponse<Object> localVarResponse = await GetObjectsAsyncWithHttpInfo(accept, type, sceneFormat, file);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Return objects Localize uploaded image and return objects info and scene
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="type">If not specified type is sticker (optional, default to sticker)</param>
        /// <param name="sceneFormat">If not specified scene_format is none (optional, default to none)</param>
        /// <param name="file">An image to make a query by (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> GetObjectsAsyncWithHttpInfo (string accept, string type = default(string), string sceneFormat = default(string), System.IO.Stream file = default(System.IO.Stream))
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'accept' when calling LocalizationApi->GetObjects");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/plain"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }
            if (sceneFormat != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "scene_format", sceneFormat));
            }
            localVarRequestOptions.HeaderParameters.Add("Accept", Org.OpenAPITools.Client.ClientUtils.ParameterToString(accept)); // header parameter
            if (file != null)
            {
                localVarRequestOptions.FileParameters.Add("file", file);
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/get_objects", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetObjects", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Localize camera Localize uploaded image. Return camera pose and optional objects info and scene. Objects info and scene are sent on coordinate system change.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="description"></param>
        /// <param name="image">A JPEG-encoded query image</param>
        /// <returns>LocalizationResult</returns>
        public LocalizationResult Localize (string accept, LocalizerLocalizeDescription description, System.IO.Stream image)
        {
             Org.OpenAPITools.Client.ApiResponse<LocalizationResult> localVarResponse = LocalizeWithHttpInfo(accept, description, image);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Localize camera Localize uploaded image. Return camera pose and optional objects info and scene. Objects info and scene are sent on coordinate system change.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="description"></param>
        /// <param name="image">A JPEG-encoded query image</param>
        /// <returns>ApiResponse of LocalizationResult</returns>
        public Org.OpenAPITools.Client.ApiResponse< LocalizationResult > LocalizeWithHttpInfo (string accept, LocalizerLocalizeDescription description, System.IO.Stream image)
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'accept' when calling LocalizationApi->Localize");

            // verify the required parameter 'description' is set
            if (description == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'description' when calling LocalizationApi->Localize");

            // verify the required parameter 'image' is set
            if (image == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'image' when calling LocalizationApi->Localize");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data", 
                "image/jpeg"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/plain"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.HeaderParameters.Add("Accept", Org.OpenAPITools.Client.ClientUtils.ParameterToString(accept)); // header parameter
            localVarRequestOptions.FormParameters.Add("description", Org.OpenAPITools.Client.ClientUtils.ParameterToString(description)); // form parameter
            localVarRequestOptions.FileParameters.Add("image", image);


            // make the HTTP request
            var localVarResponse = this.Client.Post< LocalizationResult >("/localizer/localize", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Localize", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Localize camera Localize uploaded image. Return camera pose and optional objects info and scene. Objects info and scene are sent on coordinate system change.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="description"></param>
        /// <param name="image">A JPEG-encoded query image</param>
        /// <returns>Task of LocalizationResult</returns>
        public async System.Threading.Tasks.Task<LocalizationResult> LocalizeAsync (string accept, LocalizerLocalizeDescription description, System.IO.Stream image)
        {
             Org.OpenAPITools.Client.ApiResponse<LocalizationResult> localVarResponse = await LocalizeAsyncWithHttpInfo(accept, description, image);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Localize camera Localize uploaded image. Return camera pose and optional objects info and scene. Objects info and scene are sent on coordinate system change.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="description"></param>
        /// <param name="image">A JPEG-encoded query image</param>
        /// <returns>Task of ApiResponse (LocalizationResult)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<LocalizationResult>> LocalizeAsyncWithHttpInfo (string accept, LocalizerLocalizeDescription description, System.IO.Stream image)
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'accept' when calling LocalizationApi->Localize");

            // verify the required parameter 'description' is set
            if (description == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'description' when calling LocalizationApi->Localize");

            // verify the required parameter 'image' is set
            if (image == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'image' when calling LocalizationApi->Localize");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data", 
                "image/jpeg"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/plain"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.HeaderParameters.Add("Accept", Org.OpenAPITools.Client.ClientUtils.ParameterToString(accept)); // header parameter
            localVarRequestOptions.FormParameters.Add("description", Org.OpenAPITools.Client.ClientUtils.ParameterToString(description)); // form parameter
            localVarRequestOptions.FileParameters.Add("image", image);


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<LocalizationResult>("/localizer/localize", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Localize", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Prepare localization session Prepare for localization for given geolocation. Causes server to load nearby reconstructions for localization. Returns an error when localization in this location is not possible.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="lat">GPS latitude</param>
        /// <param name="lon">GPS longitude</param>
        /// <param name="alt">GPS altitude (optional) (optional)</param>
        /// <param name="dop">GPS HDOP (optional) (optional)</param>
        /// <returns>Status</returns>
        public Status Prepare (string accept, double lat, double lon, double? alt = default(double?), double? dop = default(double?))
        {
             Org.OpenAPITools.Client.ApiResponse<Status> localVarResponse = PrepareWithHttpInfo(accept, lat, lon, alt, dop);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Prepare localization session Prepare for localization for given geolocation. Causes server to load nearby reconstructions for localization. Returns an error when localization in this location is not possible.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="lat">GPS latitude</param>
        /// <param name="lon">GPS longitude</param>
        /// <param name="alt">GPS altitude (optional) (optional)</param>
        /// <param name="dop">GPS HDOP (optional) (optional)</param>
        /// <returns>ApiResponse of Status</returns>
        public Org.OpenAPITools.Client.ApiResponse< Status > PrepareWithHttpInfo (string accept, double lat, double lon, double? alt = default(double?), double? dop = default(double?))
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'accept' when calling LocalizationApi->Prepare");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/plain"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "lat", lat));
            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "lon", lon));
            if (alt != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "alt", alt));
            }
            if (dop != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "dop", dop));
            }
            localVarRequestOptions.HeaderParameters.Add("Accept", Org.OpenAPITools.Client.ClientUtils.ParameterToString(accept)); // header parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get< Status >("/localizer/prepare", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Prepare", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Prepare localization session Prepare for localization for given geolocation. Causes server to load nearby reconstructions for localization. Returns an error when localization in this location is not possible.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="lat">GPS latitude</param>
        /// <param name="lon">GPS longitude</param>
        /// <param name="alt">GPS altitude (optional) (optional)</param>
        /// <param name="dop">GPS HDOP (optional) (optional)</param>
        /// <returns>Task of Status</returns>
        public async System.Threading.Tasks.Task<Status> PrepareAsync (string accept, double lat, double lon, double? alt = default(double?), double? dop = default(double?))
        {
             Org.OpenAPITools.Client.ApiResponse<Status> localVarResponse = await PrepareAsyncWithHttpInfo(accept, lat, lon, alt, dop);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Prepare localization session Prepare for localization for given geolocation. Causes server to load nearby reconstructions for localization. Returns an error when localization in this location is not possible.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="lat">GPS latitude</param>
        /// <param name="lon">GPS longitude</param>
        /// <param name="alt">GPS altitude (optional) (optional)</param>
        /// <param name="dop">GPS HDOP (optional) (optional)</param>
        /// <returns>Task of ApiResponse (Status)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Status>> PrepareAsyncWithHttpInfo (string accept, double lat, double lon, double? alt = default(double?), double? dop = default(double?))
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'accept' when calling LocalizationApi->Prepare");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/plain"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "lat", lat));
            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "lon", lon));
            if (alt != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "alt", alt));
            }
            if (dop != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "dop", dop));
            }
            localVarRequestOptions.HeaderParameters.Add("Accept", Org.OpenAPITools.Client.ClientUtils.ParameterToString(accept)); // header parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Status>("/localizer/prepare", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Prepare", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
