/* 
 * Augmented City API
 *
 * ## Description This is an API for the Augmented City platform ## Other resources For more information, please visit our website [https://www.augmented.city](https://www.augmented.city/) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@vergendo.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IObjectApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Add an object
        /// </summary>
        /// <remarks>
        /// Add a new user object into database
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="image"></param>
        /// <param name="description"></param>
        /// <returns>Object</returns>
        Object AddObject (string accept, System.IO.Stream image, StickerDescription description);

        /// <summary>
        /// Add an object
        /// </summary>
        /// <remarks>
        /// Add a new user object into database
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="image"></param>
        /// <param name="description"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> AddObjectWithHttpInfo (string accept, System.IO.Stream image, StickerDescription description);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IObjectApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Add an object
        /// </summary>
        /// <remarks>
        /// Add a new user object into database
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="image"></param>
        /// <param name="description"></param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> AddObjectAsync (string accept, System.IO.Stream image, StickerDescription description);

        /// <summary>
        /// Add an object
        /// </summary>
        /// <remarks>
        /// Add a new user object into database
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="image"></param>
        /// <param name="description"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddObjectAsyncWithHttpInfo (string accept, System.IO.Stream image, StickerDescription description);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IObjectApi : IObjectApiSync, IObjectApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ObjectApi : IObjectApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ObjectApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ObjectApi(String basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ObjectApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ObjectApi(Org.OpenAPITools.Client.ISynchronousClient client,Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Add an object Add a new user object into database
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="image"></param>
        /// <param name="description"></param>
        /// <returns>Object</returns>
        public Object AddObject (string accept, System.IO.Stream image, StickerDescription description)
        {
             Org.OpenAPITools.Client.ApiResponse<Object> localVarResponse = AddObjectWithHttpInfo(accept, image, description);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Add an object Add a new user object into database
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="image"></param>
        /// <param name="description"></param>
        /// <returns>ApiResponse of Object</returns>
        public Org.OpenAPITools.Client.ApiResponse< Object > AddObjectWithHttpInfo (string accept, System.IO.Stream image, StickerDescription description)
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'accept' when calling ObjectApi->AddObject");

            // verify the required parameter 'image' is set
            if (image == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'image' when calling ObjectApi->AddObject");

            // verify the required parameter 'description' is set
            if (description == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'description' when calling ObjectApi->AddObject");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/plain"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.HeaderParameters.Add("Accept", Org.OpenAPITools.Client.ClientUtils.ParameterToString(accept)); // header parameter
            localVarRequestOptions.FileParameters.Add("image", image);
            localVarRequestOptions.FormParameters.Add("description", Org.OpenAPITools.Client.ClientUtils.ParameterToString(description)); // form parameter


            // make the HTTP request
            var localVarResponse = this.Client.Post< Object >("/object", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddObject", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add an object Add a new user object into database
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="image"></param>
        /// <param name="description"></param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> AddObjectAsync (string accept, System.IO.Stream image, StickerDescription description)
        {
             Org.OpenAPITools.Client.ApiResponse<Object> localVarResponse = await AddObjectAsyncWithHttpInfo(accept, image, description);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Add an object Add a new user object into database
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept"></param>
        /// <param name="image"></param>
        /// <param name="description"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> AddObjectAsyncWithHttpInfo (string accept, System.IO.Stream image, StickerDescription description)
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'accept' when calling ObjectApi->AddObject");

            // verify the required parameter 'image' is set
            if (image == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'image' when calling ObjectApi->AddObject");

            // verify the required parameter 'description' is set
            if (description == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'description' when calling ObjectApi->AddObject");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/plain"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.HeaderParameters.Add("Accept", Org.OpenAPITools.Client.ClientUtils.ParameterToString(accept)); // header parameter
            localVarRequestOptions.FileParameters.Add("image", image);
            localVarRequestOptions.FormParameters.Add("description", Org.OpenAPITools.Client.ClientUtils.ParameterToString(description)); // form parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/object", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddObject", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
